---
- name: Playbook to configure execution environments
  hosts: builder
  connection: local
  gather_facts: false
  vars_files:
    - "../builder_eei_conf.yml"
    - "../vault.yml"
  tasks:
    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
...